/**:
  ros__parameters:
    plugin_denylist:
      # common
      - actuator_control
      - adsb
      - altitude
      - cam_imu_sync
      - camera
      - cellular_status
      # - command
      - companion_process_status
      # - esc_status
      - esc_telemetry
      - fake_gps
      - geofence
      - gimbal_control
      - global_position
      - gps_input
      - gps_rtk
      - gps_status
      - hil
      - home_position
      - landing_target
      # - local_position
      # - log_transfer
      - mag_calibration_status
      - manual_control
      - mocap_pose_estimate
      - mount_control
      - nav_controller_output
      - obstacle_distance
      - odometry
      - onboard_computer_status
      - open_drone_id
      - optical_flow
      - param
      - play_tune
      - px4flow
      - rally_point
      - rangefinder
      # - rc_io
      - setpoint_accel
      - setpoint_attitude
      - setpoint_position
      - setpoint_raw
      - setpoint_trajectory
      - setpoint_velocity
      # - sys_status
      # - sys_time
      - tdr_radio
      - terrain
      - trajectory
      - tunnel
      - vfr_hud
      # - vision_pose
      # - vision_speed
      - waypoint
      - wheel_odometry
      - wind_estimation

      # extras
      - image_pub
      - vibration
      - distance_sensor
      - rangefinder
      - wheel_odometry

    # plugin_allowlist:
    #   - 'sys_*'